//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B2BSCMDb : DbContext
    {
        public B2BSCMDb()
            : base("name=B2BSCMDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MS_BP> MS_BP { get; set; }
        public virtual DbSet<MS_BP_CP> MS_BP_CP { get; set; }
        public virtual DbSet<MS_COUNTRY> MS_COUNTRY { get; set; }
        public virtual DbSet<MS_DOCTYPE> MS_DOCTYPE { get; set; }
        public virtual DbSet<MS_PORT> MS_PORT { get; set; }
        public virtual DbSet<MS_URL> MS_URL { get; set; }
        public virtual DbSet<MS_USER> MS_USER { get; set; }
        public virtual DbSet<TRX> TRX { get; set; }
        public virtual DbSet<TRX_DOC> TRX_DOC { get; set; }
        public virtual DbSet<TRX_DTL> TRX_DTL { get; set; }
        public virtual DbSet<TRX_SHP> TRX_SHP { get; set; }
        public virtual DbSet<TRX_AWB> TRX_AWB { get; set; }
        public virtual DbSet<TRX_DOC_HEADER> TRX_DOC_HEADER { get; set; }
    }
}
