//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_DOCTYPE
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<bool> Secure { get; set; }
        public Nullable<bool> Bfm_Scm { get; set; }
        public Nullable<bool> Bfm_Finance { get; set; }
        public Nullable<bool> Seller { get; set; }
        public Nullable<bool> Shipper { get; set; }
    }
}
