//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_USER
    {
        public string Usr { get; set; }
        public string Pwd { get; set; }
        public string Fn { get; set; }
        public string AccountType { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string VendorCode { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdBy { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<int> Failed { get; set; }
    }
}
