//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX
    {
        public string PurchaseNo1 { get; set; }
        public long PurchaseNo2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> TradeQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> ShipmentFrom { get; set; }
        public Nullable<System.DateTime> ShipmentTo { get; set; }
        public string Origin { get; set; }
        public string Shipper { get; set; }
        public string Seller { get; set; }
        public string Remark { get; set; }
        public string RequiredDoc { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdBy { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<decimal> FinalUnitPrice { get; set; }
        public Nullable<System.DateTime> LTCCommDiscDate { get; set; }
        public Nullable<System.DateTime> LTCCompDiscDate { get; set; }
        public Nullable<bool> LTCConfirm { get; set; }
        public string LTCConfirmBy { get; set; }
        public Nullable<System.DateTime> LTCConfirmDate { get; set; }
        public string StatusDesDem { get; set; }
        public Nullable<decimal> Rates { get; set; }
        public string Currency { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedBy { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<System.DateTime> LTCDueDate { get; set; }
        public Nullable<System.DateTime> LTCPaymentDueDate { get; set; }
    }
}
