//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DTL
    {
        public long Uid { get; set; }
        public long PurchaseNo2 { get; set; }
        public string WheatCode { get; set; }
        public string WheatName { get; set; }
        public string DiscPort { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> FinalQty { get; set; }
        public string LoadPort { get; set; }
        public Nullable<System.DateTime> ETALoad { get; set; }
        public Nullable<System.DateTime> ETBLoad { get; set; }
        public Nullable<System.DateTime> ETDLoad { get; set; }
        public Nullable<System.DateTime> ETADisc { get; set; }
        public Nullable<System.DateTime> ETBDisc { get; set; }
        public Nullable<System.DateTime> ETCDisc { get; set; }
        public string Guid { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
    }
}
