//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_AWB
    {
        public long Uid { get; set; }
        public Nullable<long> PurchaseNo2 { get; set; }
        public string AWB { get; set; }
        public string Courier { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdBy { get; set; }
        public string Ctgry { get; set; }
    }
}
