//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DOC_HEADER
    {
        public long Uid { get; set; }
        public long PurchaseNo2 { get; set; }
        public string AttachmentName { get; set; }
        public int DocType { get; set; }
        public Nullable<int> AttachmentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Trx_Doc_Id { get; set; }
        public string Guid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
